version: "3.9"
services:
  app:
    restart: always
    build:
      context: context
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./tmp:/tmp
    command:
      python main.py